export const USER_CREATE_REQUEST = "USER_CREATE_REQUEST";
export const USER_CREATE_SUCCESS = "USER_CREATE_SUCCESS";
export const USER_CREATE_FAILURE = "USER_CREATE_FAILURE";

export const GET_USERLIST_REQUEST = 'GET_USERLIST_REQUEST';
export const GET_USERLIST_SUCCESS = 'GET_USERLIST_SUCCESS';
export const GET_USERLIST_ERROR = 'GET_USERLIST_ERROR';

export const GET_USERBYID_REQUEST = 'GET_USERBYID_REQUEST';
export const GET_USERBYID_SUCCESS = 'GET_USERBYID_SUCCESS';
export const GET_USERBYID_ERROR = 'GET_USERBYID_ERROR';

export const USER_UPDATE_REQUEST = "USER_UPDATE_REQUEST";
export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS";
export const USER_UPDATE_FAILURE = "USER_UPDATE_FAILURE";

export const USER_DELETE_REQUEST = "USER_DELETE_REQUEST";
export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS";
export const USER_DELETE_FAILURE = "USER_DELETE_FAILURE";
export const USER_FAILURE = "USER_FAILURE"